### ISSUE TITLE
howto?

### ISSUE THREAD

**Issue by magwas** [MarkusBernhardt/xml-doclet#8]
Well, I may be dumb, but can't figure out how to use xml-doclet.
mvn javadoc:javadoc creates the html documentation, but does not create any xml file beyond
target/javadoc-bundle-options/javadoc-options-javadoc-resources.xml

the pom.xml is here: https://github.com/magwas/PDEngine/blob/167b071b874d9a676d5912da8c52c042daffd8a5/pom.xml

**Comment by magwas** [comment]
... and I cannot find xml-doclet in ~/.m2 after mvn javadoc:javadoc

**Comment by MarkusBernhardt** [comment]
Hmm. Thanks for your input. It seems not to wok, when executed standalone.

Please add **&lt;phase&gt;prepare-package&lt;/phase&gt;** to your pom.xml to activate the generation of javadoc in the standard maven lifecycle. 

```xml
    <id>xml-doclet</id>
    <phase>prepare-package</phase>
    <goals>
        <goal>javadoc</goal>
    </goals>
```

Then execute
```
    mvn package
```

**Comment by magwas** [comment]
This works, thank you. Here is a pull request as a sign of gratitude.

**Comment by MarkusBernhardt** [comment]
Thanks a lot!
